"""Bilingual worksheet PDF - generated locally with fpdf2.

fpdf2 with the harfbuzz shaping engine enabled is what makes this work
offline: Devanagari conjuncts and Ol Chiki both need real text shaping,
which reportlab-style glyph-by-glyph rendering cannot do. Both fonts are
bundled locally (downloaded once by scripts/download_models.py into
frontend/fonts/), so no network is involved at print time.
"""

from __future__ import annotations

import random
import time

from fpdf import FPDF

from .. import config
from ..engines.base import ModelUnavailable

DEVA_FONT = config.FRONTEND_DIR / "fonts" / "NotoSansDevanagari-Regular.ttf"
OLCHIKI_FONT = config.FRONTEND_DIR / "fonts" / "NotoSansOlChiki-Regular.ttf"

FOOTER_NOTE = (
    "Generated by MaatraVani (local, offline). Machine-generated translation - "
    "please review before classroom use."
)


def _ensure_fonts() -> None:
    missing = [str(p) for p in (DEVA_FONT, OLCHIKI_FONT) if not p.exists()]
    if missing:
        raise ModelUnavailable(
            "Worksheet fonts not downloaded ("
            + ", ".join(missing)
            + "). Run scripts/download_models.py once while online."
        )


class WorksheetPDF(FPDF):
    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.set_text_shaping(use_shaping_engine=True)
        self.add_font("deva", "", str(DEVA_FONT))
        self.add_font("olck", "", str(OLCHIKI_FONT))
        self.set_auto_page_break(auto=True, margin=18)

    def header(self):
        self.set_font("helvetica", size=15)
        self.set_text_color(217, 108, 47)
        self.cell(0, 8, "MAATRAVANI", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("deva", size=11)
        self.set_text_color(40, 48, 43)
        self.cell(0, 7, "द्विभाषी शिक्षण कार्यपत्रक  ·  Bilingual Learning Worksheet",
                  align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        self.set_draw_color(217, 108, 47)
        self.set_line_width(0.6)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_font("helvetica", size=7.5)
        self.set_text_color(120, 120, 120)
        self.multi_cell(0, 4, FOOTER_NOTE, align="C")
        self.set_font("helvetica", size=8)
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="C")


def build_worksheet(topic: str, grade: str, outcome: str,
                    vocabulary: list[dict],
                    instruction: dict | None = None) -> bytes:
    """vocabulary: [{hi, sat, icon?...}] from the lesson generator.
    instruction: optional {"hi": ..., "sat": ...} matching-activity line."""
    _ensure_fonts()
    if not vocabulary:
        raise ModelUnavailable("no vocabulary to put on the worksheet")
    instruction = instruction or {"hi": "गतिविधि: सही जोड़े मिलाइए।", "sat": ""}

    pdf = WorksheetPDF()
    pdf.add_page()

    # -- meta row -----------------------------------------------------------
    today = time.strftime("%d/%m/%Y")
    pdf.set_font("deva", size=10.5)
    pdf.multi_cell(0, 6,
                   f"विषय: {topic}    ·    कक्षा: {grade}    ·    दिनांक: {today}",
                   align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(0, 6, f"सीखने का उद्देश्य: {outcome}", align="L",
                   new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # -- vocabulary table ----------------------------------------------------
    pdf.set_font("deva", size=13)
    pdf.set_fill_color(250, 244, 234)
    pdf.cell(90, 9, "हिन्दी", border=1, align="C", fill=True)
    pdf.set_font("olck", size=13)
    pdf.cell(90, 9, "ᱥᱟᱱᱛᱟᱲᱤ", border=1, align="C", fill=True, new_x="LMARGIN", new_y="NEXT")
    for w in vocabulary:
        pdf.set_font("deva", size=12)
        pdf.cell(90, 10, w["hi"], border=1, align="C")
        pdf.set_font("olck", size=12)
        pdf.cell(90, 10, w["sat"], border=1, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # -- matching activity ----------------------------------------------------
    # Bilingual strings arrive pre-translated from the generator's
    # lexicon/NLLB chain - nothing is hand-invented here.
    rng = random.Random(2026)  # deterministic shuffle, so the answer key holds
    right = vocabulary[:6]
    shuffled = list(right)
    rng.shuffle(shuffled)

    pdf.set_font("deva", size=13)
    pdf.multi_cell(0, 8, instruction["hi"], new_x="LMARGIN", new_y="NEXT")
    if instruction.get("sat"):
        pdf.set_font("olck", size=10)
        pdf.multi_cell(0, 6, instruction["sat"], new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    col_top = pdf.get_y()
    row_h = 11
    for i, w in enumerate(right):
        pdf.set_font("deva", size=12)
        pdf.set_xy(15, col_top + i * row_h)
        pdf.cell(6, row_h, f"{i + 1}.", border=0)
        pdf.cell(50, row_h, w["hi"], border=0)
    for j, w in enumerate(shuffled):
        pdf.set_font("olck", size=12)
        pdf.set_xy(110, col_top + j * row_h)
        pdf.cell(6, row_h, f"{chr(97 + j)}.", border=0)
        pdf.cell(60, row_h, w["sat"], border=0)
    pdf.set_y(col_top + len(right) * row_h + 4)

    # -- draw box ---------------------------------------------------------------
    pdf.set_font("deva", size=12)
    pdf.multi_cell(0, 8, f"अपना पसंदीदा चित्र बनाइए ({topic}):",
                   new_x="LMARGIN", new_y="NEXT")
    top = pdf.get_y()
    pdf.set_draw_color(180, 180, 180)
    pdf.rect(15, top, 180, 55)
    pdf.set_y(top + 58)

    return bytes(pdf.output())
